name: Jekyll Version of Pattern Primer
markdown: kramdown
# baseurl should be set to:
# '': for local development (localhost:4000)
# '': for root level domains (mycustomdomain.com)
# '/projectname': for subdomains (user.github.io/projectname)
baseurl: 'designsystem'
permalink: :title.html

collections:
  buttons:
    output: true
    permalink: patterns/:path/
  typography:
    output: true
    permalink: typography/:path/
  navigation:
    output: true
    permalink: navigation/:path/
  forms:
    output: true
    permalink: forms/:path/

markdown-patterns: false
